"""initial schema: users, matches, jobs, events

Revision ID: 0001
Revises:
Create Date: 2026-08-05

Hand-written (not autogenerated, since the sandbox has no live Postgres to diff
against — see dev/DECISIONS.md ADR-007). Mirrors api/app/models.py exactly;
re-run `alembic check` on the Mac before trusting this blindly on first use.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

match_status_enum = sa.Enum(
    "uploaded", "validating", "transcoding", "tracking", "extracting_pose",
    "classifying_states", "detecting_events", "generating_insights", "complete", "failed",
    name="matchstatus",
)
job_stage_status_enum = sa.Enum("pending", "running", "complete", "failed", name="jobstagestatus")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "matches",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.String(), nullable=False, server_default="Untitled match"),
        sa.Column("style", sa.String(), server_default="folkstyle"),
        sa.Column("status", match_status_enum, nullable=False, server_default="uploaded"),
        sa.Column("video_keys", sa.JSON(), server_default="{}"),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("meta", sa.JSON(), server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_matches_user_id", "matches", ["user_id"])

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("match_id", sa.String(), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("status", job_stage_status_enum, nullable=False, server_default="pending"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("artifacts", sa.JSON(), server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_jobs_match_id", "jobs", ["match_id"])

    op.create_table(
        "events",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("match_id", sa.String(), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(), server_default="human"),
        sa.Column("clip_key", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_events_match_id", "events", ["match_id"])


def downgrade() -> None:
    op.drop_table("events")
    op.drop_table("jobs")
    op.drop_table("matches")
    op.drop_table("users")
    match_status_enum.drop(op.get_bind(), checkfirst=True)
    job_stage_status_enum.drop(op.get_bind(), checkfirst=True)
